### ISSUE TITLE
Friendly Note on "Automatic Rao-Blackwellization for Sequential Monte Carlo with Belief Propagation"

### ISSUE THREAD

**Issue by albertpod** [wazizian/OnlineSampling.jl#60]
Hi authors,
 
I hope you are doing well. I've tried to reach you out with the following email: waiss (dot) azizian (at) univ-grenoble-alpes (dot) fr, but the delivery has failed, according to DNS.
 
I recently read your publication, _"Automatic Rao-Blackwellization for Sequential Monte Carlo with Belief Propagation,"_ and wanted to acknowledge your work. It's heartening to witness active contributions to the field.
 
In your study, you mentioned `ReactiveMP.jl`, a package I had the pleasure to co-author, and contribute to. For your information and any future references, as of 2022, `ReactiveMP.jl` has been subsumed into `RxInfer.jl`.
 
`RxInfer.jl `extends the scope of ReactiveMP.jl and offers a variety of hybrid inference algorithms to handle models with loops, non-linearities, and non-conjugacy. These inference algorithms have been backed by extensive research from our lab, [BIASlab](https://biaslab.github.io/publication/). Interestingly, `RxInfer.jl` can also execute all the examples in your `OnlineSampling.jl `package. This makes `RxInfer.jl `a comprehensive solution for a diverse array of complex models.
 
While reading your paper, I thought this update might be relevant to you, as it could bring additional perspectives to your future research.
 
Once again, congratulations on your recent publication, and I look forward to seeing your future works.
 
Best Regards,

**Comment by mlelarge** [comment]
Thanks @albertpod, for your note, and we will update our citations. Just to be sure, I think the main difference between [RxInfer.jl](https://github.com/biaslab/RxInfer.jl) and our approach is that you rely on variational method when exact inference is not possible whereas we are relying on simulation. So both approaches are indeed complementary.

**Comment by albertpod** [comment]
Hi @mlelarge! Thanks for the reply! When inference isn't tractable, `RxInfer.jl` offers a few ways of circumventing this, which is either using [sampling](https://biaslab.github.io/RxInfer.jl/stable/examples/problem_specific/Simple%20Nonlinear%20Node/), [linearization, unscented transform](https://biaslab.github.io/RxInfer.jl/stable/examples/basic_examples/Kalman%20filtering%20and%20smoothing/#Combination-1:-y-x-w) or [CVI](https://biaslab.github.io/RxInfer.jl/stable/examples/advanced_examples/Nonlinear%20Sensor%20Fusion/). In the future release this will be automated. 
Good work, guys! Looking forward seeing more!
